name: pull-request-checks
on: [pull_request]
jobs:
  verify-code:
    name: Building action and running tests
    runs-on: windows-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Build
        run: npm run prepare
      
      - name: Run Tests
        run: npm run test

  invoke-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
